/*
obs-plugin-countdown-adu - UI preview harness
Copyright (C) 2026

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>
*/

/*
 * Standalone replacement for OBS's obs_module_text().
 *
 * The real implementation is generated by the OBS_MODULE_USE_DEFAULT_LOCALE
 * macro and depends on libobs. In the harness we don't link libobs, so we
 * provide a lightweight lookup that parses the plugin's en-US.ini locale file
 * (format: Key="Value") and returns stable, cached strings. Unknown keys fall
 * back to the key itself, matching OBS behaviour.
 */

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <fstream>
#include <mutex>
#include <string>
#include <unordered_map>

#ifndef COUNTDOWN_LOCALE_FILE
#define COUNTDOWN_LOCALE_FILE ""
#endif

namespace {

std::string unquote(std::string value)
{
	/* Trim surrounding whitespace. */
	const auto notSpace = [](unsigned char c) { return !std::isspace(c); };
	value.erase(value.begin(), std::find_if(value.begin(), value.end(), notSpace));
	value.erase(std::find_if(value.rbegin(), value.rend(), notSpace).base(), value.end());

	/* Strip surrounding double quotes if present. */
	if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
		value = value.substr(1, value.size() - 2);
	}
	return value;
}

std::unordered_map<std::string, std::string> &table()
{
	static std::unordered_map<std::string, std::string> t;
	static std::once_flag once;

	std::call_once(once, [] {
		const char *path = COUNTDOWN_LOCALE_FILE;
		std::ifstream file(path);
		if (!file.is_open()) {
			std::fprintf(stderr, "[harness] could not open locale file: %s\n", path);
			return;
		}

		std::string line;
		while (std::getline(file, line)) {
			/* Skip comments and blank lines. */
			std::string trimmed = unquote(line);
			if (trimmed.empty() || trimmed[0] == '#' || trimmed[0] == ';') {
				continue;
			}

			const auto eq = line.find('=');
			if (eq == std::string::npos) {
				continue;
			}

			std::string key = unquote(line.substr(0, eq));
			std::string value = unquote(line.substr(eq + 1));
			if (!key.empty()) {
				t[key] = value;
			}
		}
	});

	return t;
}

} // namespace

extern "C" const char *obs_module_text(const char *val)
{
	if (!val) {
		return "";
	}

	auto &t = table();
	auto it = t.find(val);
	if (it != t.end()) {
		return it->second.c_str();
	}

	/* Fallback: cache and return the key itself so the pointer stays valid. */
	auto inserted = t.emplace(val, val);
	return inserted.first->second.c_str();
}
